### ISSUE TITLE
dataset format ?

### ISSUE THREAD

**Issue by wlz987** [ZeningLin/PEneo#5]
能具体讲讲怎么生成自定义的 dataset 吗,还有其他配置怎么改

**Comment by ZeningLin** [comment]
最近事情过多，抱歉没能及时回复

数据集方面，您可以参考`data/datasets/sibr.py`中的操作进行私有数据的适配。该文件对数据进行了以下的操作

1. 遍历标注数据，获取每一行文本的内容、坐标、标签等
2. 根据坐标，调用sort_boxes对文本行进行左上右下排序
3. 按照排序顺序，读取每一行的信息，进行如下操作
    a. 使用tokenizer将文本切分为token。注意到tokenizer分词时，会去除部分空格，加入特殊的标记符号。为了在后处理阶段能将token级别的信息还原为实体级别的信息，这里额外设置了tokenizer_fetcher，通过比对分词前后的文本序列，将token中被删除/添加的字符恢复原状
    b. 生成与token一一对应的bbox序列。留意到backbone是需要将bbox归一化到1-1000的范围内的。同时为了方便后续可视化，我们还要将生成一个存放原始bbox值的序列orig_bbox
    c. 统计每一行的起止token位置，生成用于line extraction任务的line_extraction_matrix_spots标签

4. 根据标签中的linking信息（存在kv关系的实体id对），生成用于entity linking任务的ent_linking_head/tail_rel_matrix_spots标签
5. 根据标签中的实体文本行聚合信息（一个实体内前后相邻的两行文本的id对），生成用于line grouping任务的line_grouping_head/tail_rel_matrix_spots标签。

SIBRDataset类中有一个ENTITY_LABEL_LIST和LABEL_LIST字段，分别存放SER标签和BIO格式的SER标签，这里需根据您的私有数据进行修改调整。

您可以参考本仓库release的SIBR revised标签，将您的数据转换为这个格式，随后便可在`data/datasets/sibr.py`的基础上做少许修改实现数据的适配。

模型结构方面，您可在`model/configuration_peneo.py`中看到几个配置的参数，它们的功能如下

- backbone_name：backbone的名称
- backbone_config：backbone模型的huggingface配置文件，您可在模型对应的huggingface model页面找到其具体内容。在PEneo中我们没有对该项进行改动。
- initializer_range：初始化的参数，保持默认即可
- peneo_decoder_shrink：backbone输出的feature维度较高，为减少下游分支的计算量，论文利用线性层将其维度减半，这里默认为True开启降维
- peneo_classifier_num_layers：下游分支中会对五个矩阵进行分类操作，这里控制分类器的线性层层数
- peneo_loss_ratio：五个矩阵分类loss的比例，置为1即可
- peneo_category_weights：下游分支中，line extraction任务进行二分类；line grouping和entity linking进行三分类。这里控制0、1、2三个类别标签计算loss时的加权系数（line extraction只看前两个值，另外两个任务三个值都看）。按照经验，该部分设为[1,10,10]较为妥当
- peneo_ohem_num_positive/negative：若设置为大于0的数k，则开启OHEM，在计算loss时选取最大的k个正/负样本进行BP，其余忽略
- peneo_downstream_speedup_ratio：下游分支学习率与backbone部分学习率的比值，按照炼丹经验设为30，也可根据数据集自行摸索调整
- inference_mode：导出onnx时需设为True，以适配trace逻辑
