### ISSUE TITLE
对SIBR数据集中的line_grouping有些疑问

### ISSUE THREAD

**Issue by l1006986533** [ZeningLin/PEneo#9]
作者您好，首先非常感谢您优秀的项目！在使用自己的数据集训练时，我遇到几个问题：
1. 在SIBR数据集中，entities已经将每个entity的lines组合成一组了，为什么还需要relations.line_grouping字段？
2. 我想要自己标注数据集，请问有什么好的标注工具推荐吗？（注：我已经有OCR工具，可以给出text和bbox，但我缺少relations中针对kv_entity（键值对配对）和line_grouping的标注工具）

**Comment by l1006986533** [comment]
[https://github.com/ZeningLin/PEneo/blob/main/docs/documentation.md#adapt-to-custom-datasets](https://github.com/ZeningLin/PEneo/blob/main/docs/documentation.md#adapt-to-custom-datasets)
```json
{
    "uid": "str <sample_id>",
    "img": {
        "fname": "str <image_file_name>",
        "width": "int <image_width>",
        "height": "int <image_height>"
    },
    "entities": [
        {
            "id": "int <entity_id>",
            "label": "str <entity_type>",
            "lines": [
                {
                    "id": "int or str <line_id>",
                    "text": "str <line_text>",
                    "bbox": [
                        "int <left>",
                        "int <top>",
                        "int <right>",
                        "int <bottom>"
                    ]
                },
                ...
            ]
        },
        ...
    ],
    "relations": {
        "kv_entity": [
            {
                "from_id": "int <key_entity_id>",
                "to_id": "int <value_entity_id>"
            },
            ...
        ],
        "line_grouping": [
            {
                "from_id": "int <prev_line_id>",
                "to_id": "int <next_line_id>"
            },
            ...
        ]
    }
}

```

**Comment by ZeningLin** [comment]
> 作者您好，首先非常感谢您优秀的项目！在使用自己的数据集训练时，我遇到几个问题：
> 
> 1. 在SIBR数据集中，entities已经将每个entity的lines组合成一组了，为什么还需要relations.line_grouping字段？
> 2. 我想要自己标注数据集，请问有什么好的标注工具推荐吗？（注：我已经有OCR工具，可以给出text和bbox，但我缺少relations中针对kv_entity（键值对配对）和line_grouping的标注工具）

你好～ 感谢你对我们工作的关注！

1. relations.line_grouping字段纯粹是为了方便PEneo的dataloader读取而设置的，其表示的组合关系和entities里面的line组合关系一致
2. 我们使用的标注平台是[Label Studio](https://labelstud.io/)，这个平台支持relation关系标注。

若有其它疑问，欢迎随时提出！

**Comment by l1006986533** [comment]
明白了，谢谢！

**Comment by l1006986533** [comment]
作者你好，Label Studio的relation关系标注是纯文本的，还是可以同时显示OCR结果的？我目前只看到能标注纯文本的标注模板，如果是在图片中将2个OCR检测框连到一起，似乎是没有现成的模板的。想问下你标注的时候，是直接在OCR纯文字结果上标注的吗，还是对照着图片标注的？

**Comment by ZeningLin** [comment]
我是对照着图片标注的，步骤略有些麻烦，方便的话加个微信交流下？

**Comment by l1006986533** [comment]
好的好的，实在太感谢了🙏
我微信号qiang1145141，id是尬聊之王
